use super::engine::SwapExecutionRecord;
use anyhow::Context;

#[derive(Debug, Clone)]
pub struct LiveFill {
    pub ts_ms: u64,
    pub input_mint: String,
    pub output_mint: String,
    pub amount_in: u64,
    pub tokens_out: u64,
    pub expected_tokens_out: Option<u64>,
}

/// Minimal CSV parser for trade logs generated by the runtime.
/// Expected headers include: timestamp_utc,side,mint,dex,signature,lamports_in,lamports_out,tokens_in,tokens_out,expected_tokens_out,expected_sol_out,shortfall_tokens,shortfall_sol,network_fee_lamports,realized_pnl_sol,notes
/// We read only fields we need; rows with missing values are skipped.
pub fn read_live_csv(path: &str) -> anyhow::Result<Vec<LiveFill>> {
    let mut rdr = csv::ReaderBuilder::new()
        .flexible(true)
        .has_headers(true)
        .from_path(path)
        .with_context(|| format!("open csv: {path}"))?;
    // Precompute header indices to avoid borrowing rdr during iteration
    let headers = rdr.headers()?.clone();
    let idx = |name: &str| headers.iter().position(|h| h == name);
    let side_idx = idx("side").ok_or_else(|| anyhow::anyhow!("missing side"))?;
    let tokens_out_idx = idx("tokens_out").ok_or_else(|| anyhow::anyhow!("missing tokens_out"))?;
    let amount_in_idx = idx("lamports_in")
        .or_else(|| idx("tokens_in"))
        .unwrap_or(tokens_out_idx);
    let expected_idx = idx("expected_tokens_out");
    let mint_idx = idx("mint");

    let mut out = Vec::new();
    for rec in rdr.records() {
        let rec = rec?;
        let side = rec.get(side_idx).unwrap_or("");
        if side != "FILL" && side != "SELL" && side != "BUY" {
            continue;
        }
        let tokens_out: u64 = rec.get(tokens_out_idx).unwrap_or("0").parse().unwrap_or(0);
        let amount_in: u64 = rec.get(amount_in_idx).unwrap_or("0").parse().unwrap_or(0);
        let expected_tokens_out = expected_idx
            .and_then(|i| rec.get(i))
            .and_then(|s| s.parse::<u64>().ok());
        // Rough mapping for mints: in real logs, "mint" refers to traded token. For validation we keep fields simple.
        let output_mint = mint_idx.and_then(|i| rec.get(i)).unwrap_or("").to_string();
        out.push(LiveFill {
            ts_ms: 0,
            input_mint: "So11111111111111111111111111111111111111112".to_string(),
            output_mint,
            amount_in,
            tokens_out,
            expected_tokens_out,
        });
    }
    Ok(out)
}

#[derive(Debug, Clone, Default)]
pub struct ValidationReport {
    pub count: usize,
    pub mae: f64,  // mean absolute error (tokens)
    pub mape: f64, // mean abs percent error
    pub within_1pct: f64,
    pub within_2pct: f64,
    pub within_5pct: f64,
}

pub fn compare_sim_vs_live(sim: &[SwapExecutionRecord], live: &[LiveFill]) -> ValidationReport {
    // naive matching by (output_mint, amount_in) multi-set; real matching would use timestamps and signatures
    use std::collections::HashMap;
    let mut buckets: HashMap<(String, u64), Vec<&SwapExecutionRecord>> = HashMap::new();
    for s in sim.iter().filter(|e| !e.rejected) {
        buckets
            .entry((s.output_mint.clone(), s.amount_in))
            .or_default()
            .push(s);
    }
    let mut n = 0usize;
    let mut abs_sum = 0f64;
    let mut abs_pct_sum = 0f64;
    let mut w1 = 0usize;
    let mut w2 = 0usize;
    let mut w5 = 0usize;
    for l in live {
        if let Some(list) = buckets.get_mut(&(l.output_mint.clone(), l.amount_in)) {
            if let Some(s) = list.pop() {
                if let Some(out) = s.amount_out {
                    let sim_out = out as f64;
                    let live_out = l.tokens_out as f64;
                    let diff = (sim_out - live_out).abs();
                    abs_sum += diff;
                    let denom = if live_out > 0.0 { live_out } else { 1.0 };
                    let pct = diff / denom;
                    abs_pct_sum += pct;
                    if pct <= 0.01 {
                        w1 += 1;
                    }
                    if pct <= 0.02 {
                        w2 += 1;
                    }
                    if pct <= 0.05 {
                        w5 += 1;
                    }
                    n += 1;
                }
            }
        }
    }
    ValidationReport {
        count: n,
        mae: if n > 0 { abs_sum / n as f64 } else { 0.0 },
        mape: if n > 0 { abs_pct_sum / n as f64 } else { 0.0 },
        within_1pct: if n > 0 { w1 as f64 / n as f64 } else { 0.0 },
        within_2pct: if n > 0 { w2 as f64 / n as f64 } else { 0.0 },
        within_5pct: if n > 0 { w5 as f64 / n as f64 } else { 0.0 },
    }
}
