[Service]
ExecStart=
ExecStart=/usr/local/bin/agave-validator \
  --identity /home/sol/validator-keypair.json \
  --ledger /var/solana/ledger \
  --limit-ledger-size 100000000 \
  --accounts /var/solana/accounts \
  --no-voting \
  --rpc-port 8899 \
  --rpc-bind-address 0.0.0.0 \
  --full-rpc-api \
  --rpc-threads 32 \
  --accounts-db-cache-limit-mb 327680 \
  --accounts-index-scan-results-limit-mb 16384 \
  --enable-rpc-transaction-history \
  --dynamic-port-range 8000-8025 \
  --tpu-connection-pool-size 1024 \
  --geyser-plugin-config /home/sol/geyser-config.json \
  --no-port-check \
  --known-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
  --known-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
  --known-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
  --known-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \
  --known-validator Ninja1spj6n9t5hVYgF3PdnYz2PLnkt7rvaw3firmjs \
  --known-validator mrgn2vsZ5EJ8YEfAMNPXmRux7th9cNfBasQ1JJvVwPn \
  --entrypoint entrypoint.mainnet-beta.solana.com:8001 \
  --entrypoint entrypoint2.mainnet-beta.solana.com:8001 \
  --entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
  --log /var/solana/validator.log
